app:
    resource: @AppBundle/Controller/
    type:     annotation

app_index:
    defaults: {_controller: AppBundle:Index:index}
    pattern: /

app_invite_code:
    defaults: {_controller: AppBundle:Index:inviteCode}
    pattern: /invite_code