i18ni18n:
    resource: "@i18ni18nBundle/Resources/config/routing.yml"
    prefix:   /

smakota_admin:
    resource: "@SmakotaAdminBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: @ClashOfKingsAppBundle/Controller/
    type:     annotation

home:
    defaults: {_controller: ClashOfKingsAppBundle:Index:index, _locale: %locale%}
    pattern: /{_locale}

app_advice:
    defaults: {_controller: ClashOfKingsAppBundle:Index:advice}
    pattern: /{_locale}/advice/{advice}

app_building_list:
    defaults: {_controller: ClashOfKingsAppBundle:Index:buildingList}
    pattern: /{_locale}/building_list