i18ni18n:
    resource: "@i18ni18nBundle/Resources/config/routing.yml"
    prefix:   /

smakota_admin:
    resource: "@SmakotaAdminBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@ClashOfKingsAppBundle/Controller/'
    type:     annotation

home:
    defaults: {_controller: ClashOfKingsAppBundle:Index:index, _locale: '%locale%'}
    path: /{_locale}

app_advice:
    defaults: {_controller: ClashOfKingsAppBundle:Index:advice}
    path: /{_locale}/advice/{advice}


building:
    resource: "@ClashOfKingsAppBundle/Controller/BuildingController.php"
    type:     annotation
    prefix:   /{_locale}/building

unit:
    resource: "@ClashOfKingsAppBundle/Controller/UnitController.php"
    type:     annotation
    prefix:   /{_locale}/unit