smakota_admin:
    resource: "@SmakotaAdminBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: @AppBundle/Controller/
    type:     annotation

app_index:
    defaults: {_controller: AppBundle:Index:index}
    pattern: /

app_advice:
    defaults: {_controller: AppBundle:Index:advice}
    pattern: /advice/{advice}