security:
    encoders:
        Smakota\Bundle\AdminBundle\Entity\User:
            algorithm: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH ]

    providers:
        administrators:
            entity: { class: SmakotaAdminBundle:User, property: username }

    firewalls:
        admin_area:
            pattern:    ^/panel.*
            form_login:
                check_path: smakota_security_check
                login_path: smakota_login
                always_use_default_target_path: true
                default_target_path: smakota_admin_panel
            logout:
                path:   smakota_logout
                target: home

    access_control:
        - { path: ^/panel, roles: ROLE_ADMIN }
