admin_panel:
    path:     /panel
    defaults: { _controller: SmakotaAdminBundle:Panel:index }
login:
    path:     /login
    defaults: { _controller: SmakotaAdminBundle:Login:login }
logout:
    path:     /panel/logout
    defaults: { _controller: SmakotaAdminBundle:Login:logout }
login_check:
    path:     /panel/login_check
    defaults: { _controller: SmakotaAdminBundle:Login:securityCheck }
